apiVersion: v1
kind: Service
metadata:
  name: hrtoolloadbalancer
  labels:
    app: hr-tool
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    name: http
    targetPort: 8000
  selector:
    app: hr-tool

